const mazdaRx7Config = {
  id: "2024 BMW M4 Coupe Competition",
  name: "2024 BMW M4 Coupe Competition",
  basePrice: 830000,

  scene: {
    cameraAngle: 12,
    cameraHeight: 1.2,
    zoom: 5.5,
    fov: 50,
    carAngle: -36,
    maxRotationX: 90,
    maxRotationY: 180,
    light: 0.45,
    shadow: 0.75,
    background: "#ffffff",
    target: [0, 0.15, 0],
    minDistance: 0,
    maxDistance: 28,
    intro: {
      enabled: true,
      startHeight: 8,
      duration: 1200,
    },
  },

  customizable: {
    steps: [
      {
        id: "paint",
        type: "paint",
        label: "Body Color",
        scene: {
          cameraAngle: 12,
          cameraHeight: 1.2,
          zoom: 5.5,
          fov: 50,
          carAngle: -36,
          maxRotationX: 90,
          maxRotationY: 180,
          light: 0.45,
          shadow: 0.75,
          background: "#ffffff",
          target: [0, 0.15, 0],
          minDistance: 0,
          maxDistance: 28,
          intro: {
            enabled: true,
            startHeight: 8,
            useLast: true,
            duration: 1200,
          },
        },
      },
      {
        id: "rims",
        type: "rims",
        label: "Rim Color",
        scene: {
          cameraAngle: 91.7,
          cameraHeight: 0.45,
          zoom: 11.74,
          fov: 20,
          carAngle: 0,
          maxRotationX: 90,
          maxRotationY: 180,
          light: 0.6,
          shadow: 0.8,
          background: "#ffffff",
          target: [0, 0, 0],
          minDistance: 0,
          maxDistance: 28,
          intro: {
            enabled: true,
            startHeight: 3,
            duration: 850,
            useLast: true,
          },
        },
      },
      {
        id: "calipers",
        type: "calipers",
        label: "Caliper Color",
        scene: {
          cameraAngle: 58.9,
          cameraHeight: -0.09,
          zoom: 16.4,
          fov: 20,
          carAngle: -34,
          maxRotationX: 2,
          maxRotationY: 2,
          light: 0.75,
          shadow: 0.82,
          background: "#ffffff",
          target: [-10.2, -0.85, -4],
          minDistance: 12.7,
          maxDistance: 28,
          intro: {
            enabled: true,
            duration: 1050,
            midpointFov: 28,
            midpointHeight: 1.1,
            midpointTarget: [0, 0, 0],
            midpointZoom: 22,
            transition: "zoom-out-in",
            useLast: true,
          },
        },
      },
    ],
  },

  paint: {
    label: "Body Color",
    defaultValue: "Dravit Grey",
    meshNames: [],
    materialNames: ["M4_2024_paint", "M4_2024_paint.001"],
    keywords: [],
    excludeKeywords: ["logo", "badge"],
    material: {
      metalness: 0.8,
      roughness: 0.2,
      clearcoat: 0.2,
      clearcoatRoughness: 0.08,
      envMapIntensity: 1.25,
    },
    colors: [
      { name: "Dravit Grey", price: 0 },
      { name: "Alpine White", price: 7900 },
      { name: "Black Sapphire", price: 12900 },
      { name: "Portimao Blue", price: 18900 },
      { name: "Tanzanite Blue", price: 18900 },
      { name: "Brooklyn Grey", price: 14900 },
      { name: "San Remo Green", price: 14900 },
    ],
    custom: {
      enabled: false,
    },
  },

  rims: {
    label: "Rim Color",
    defaultValue: "Silver",
    meshNames: [
      "M4_2024_wheels_m_black_M4_2024_Black_0",
      "M4_2024_wheels_m_black.001_M4_2024_Black_0",
      "M4_2024_wheels_m_black.002_M4_2024_Black_0",
      "M4_2024_wheels_m_black.003_M4_2024_Black_0",
    ],
    materialNames: [],
    keywords: [],
    excludeKeywords: ["logo", "badge", "hub"],
    colors: [
      { name: "Silver", price: 0 },
      { name: "Gunmetal", price: 5900 },
      { name: "Black", price: 5900 },
      { name: "Bronze", price: 9900 },
      { name: "White", price: 3900 },
    ],
    custom: {
      enabled: false,
    },
  },

  calipers: {
    label: "Caliper Color",
    defaultValue: "Black",
    meshNames: [],
    materialNames: [],
    keywords: ["calip_"],
    material: {
      metalness: 0.35,
      roughness: 0.28,
      clearcoat: 0.35,
      clearcoatRoughness: 0.16,
      envMapIntensity: 0.9,
    },
    colors: [
      { name: "Black", price: 0 },
      { name: "M Red", price: 3900 },
      { name: "Blue", price: 4900 },
      { name: "Gold", price: 5900 },
      { name: "Silver", price: 3900 },
    ],
    custom: {
      enabled: false,
    },
  },
};

export default mazdaRx7Config;
