const BMW_M4_Coupe_Competition = {
  id: "2024 BMW M4 Coupe Competition",
  name: "2024 BMW M4 Coupe Competition",
  basePrice: 830000,

  scene: {
    cameraAngle: 12,
    cameraHeight: 1.2,
    zoom: 5.5,
    fov: 50,
    carAngle: -36,
    maxRotationX: 90,
    maxRotationY: 180,
    light: 0.45,
    shadow: 0.75,
    background: "#ffffff",
    target: [0, 0.15, 0],
    minDistance: 0,
    maxDistance: 28,
    intro: {
      enabled: true,
      startHeight: 8,
      duration: 1200,
    },
  },

  orderScene: {
    cameraAngle: 16,
    cameraHeight: 1.05,
    zoom: 6.7,
    fov: 45,
    carAngle: 0,
    target: [0, 0.2, 0],
    intro: {
      enabled: false,
    },
  },

  customizable: {
    steps: [
      {
        id: "paint",
        type: "paint",
        label: "Body Color",
        scene: {
          cameraAngle: 12,
          cameraHeight: 1.2,
          zoom: 5.5,
          fov: 50,
          carAngle: -36,
          maxRotationX: 90,
          maxRotationY: 180,
          light: 0.45,
          shadow: 0.75,
          background: "#ffffff",
          target: [0, 0.15, 0],
          minDistance: 0,
          maxDistance: 28,
          intro: {
            enabled: true,
            startHeight: 8,
            useLast: true,
            duration: 1200,
          },
        },
      },
      {
        id: "rims",
        type: "rims",
        label: "Rim Color",
        scene: {
          cameraAngle: 90,
          cameraHeight: 0.45,
          zoom: 11.69,
          fov: 20,
          carAngle: 0,
          maxRotationX: 90,
          maxRotationY: 180,
          light: 0.6,
          shadow: 0.8,
          background: "#ffffff",
          target: [0, -0.25, -0.15],
          minDistance: 0,
          maxDistance: 28,
          intro: {
            enabled: true,
            startHeight: 3,
            duration: 850,
            transition: "orbit",
            useLast: true,
          },
        },
      },
      {
        id: "calipers",
        type: "calipers",
        label: "Caliper Color",
        scene: {
          light: 0.75,
          shadow: 0.82,
          positions: [
            {
              id: "focus",
              label: "Focused",
              scene: {
                cameraAngle: 90,
                cameraHeight: -0.09,
                zoom: 6.71,
                fov: 20,
                carAngle: 0,
                maxRotationX: 90,
                maxRotationY: 180,
                background: "#ffffff",
                target: [0, -0.35, 1.8],
                minDistance: 5,
                maxDistance: 28,
              },
            },
            {
              id: "profile",
              label: "Full Profile",
              scene: {
                cameraAngle: 90,
                cameraHeight: 0.5,
                zoom: 9.8,
                fov: 30,
                carAngle: 0,
                maxRotationX: 90,
                maxRotationY: 180,
                background: "#ffffff",
                target: [0, 0.1, 0.15],
                minDistance: 5,
                maxDistance: 28,
              },
            },
          ],
          intro: {
            enabled: true,
            startHeight: 8,
            duration: 1050,
            transition: "orbit",
            useLast: true,
          },
        },
      },
      {
        id: "seats",
        type: "seats",
        label: "Seat Colors",
        scene: {
          light: 0.5,
          shadow: 0.35,
          positions: [
            {
              id: "inside",
              label: "Inside",
              scene: {
                cameraAngle: 0,
                cameraHeight: 0.7,
                zoom: 0.16,
                fov: 85,
                carAngle: 0,
                maxRotationX: 360,
                maxRotationY: 360,
                background: "#ffffff",
                target: [0, 0.6, 0.3],
                minDistance: 0.12,
                maxDistance: 0.12,
              },
            },
            {
              id: "outside",
              label: "Outside",
              scene: {
                cameraAngle: 27.2,
                cameraHeight: 1.66,
                zoom: 3.79,
                fov: 46,
                carAngle: -18,
                maxRotationX: 90,
                maxRotationY: 180,
                light: 0.5,
                shadow: 0.35,
                background: "#ffffff",
                target: [0, 0.45, 0],
                minDistance: 3.8,
                maxDistance: 10.5,
                intro: {
                  enabled: false,
                  startHeight: 1.9,
                  duration: 700,
                  transition: "orbit",
                  useLast: false,
                },
              },
            },
          ],
          intro: {
            enabled: false,
            startHeight: 1.9,
            duration: 700,
            transition: "orbit",
            useLast: false,
          },
        }
      },
    ],
  },

  paint: {
    label: "Body Color",
    defaultValue: "Dravit Grey",
    meshNames: [],
    materialNames: ["M4_2024_paint", "M4_2024_paint.001"],
    keywords: [],
    excludeKeywords: ["logo", "badge"],
    material: {
      metalness: 0.8,
      roughness: 0.2,
      clearcoat: 0.2,
      clearcoatRoughness: 0.08,
      envMapIntensity: 1.25,
    },
    colors: [
      { name: "Dravit Grey", price: 0 },
      { name: "Alpine White", price: 7900 },
      { name: "Black Sapphire", price: 12900 },
      { name: "Portimao Blue", price: 18900 },
      { name: "Tanzanite Blue", price: 18900 },
      { name: "Brooklyn Grey", price: 14900 },
      { name: "San Remo Green", price: 14900 },
    ],
    custom: {
      enabled: false,
    },
  },

  rims: {
    label: "Rim Color",
    defaultValue: "Silver",
    meshNames: [
      "M4_2024_wheels_m_black_M4_2024_Black_0",
      "M4_2024_wheels_m_black.001_M4_2024_Black_0",
      "M4_2024_wheels_m_black.002_M4_2024_Black_0",
      "M4_2024_wheels_m_black.003_M4_2024_Black_0",
    ],
    materialNames: [],
    keywords: [],
    excludeKeywords: ["logo", "badge", "hub"],
    colors: [
      { name: "Silver", price: 0 },
      { name: "Gunmetal", price: 5900 },
      { name: "Black", price: 5900 },
      { name: "Bronze", price: 9900 },
      { name: "White", price: 3900 },
    ],
    custom: {
      enabled: false,
    },
  },

  calipers: {
    label: "Caliper Color",
    defaultValue: "Black",
    meshNames: [],
    materialNames: [],
    keywords: ["calip_"],
    material: {
      metalness: 0.35,
      roughness: 0.28,
      clearcoat: 0.35,
      clearcoatRoughness: 0.16,
      envMapIntensity: 0.9,
    },
    colors: [
      { name: "Black", price: 0 },
      { name: "M Red", price: 3900 },
      { name: "Blue", price: 4900 },
      { name: "Gold", price: 5900 },
      { name: "Silver", price: 3900 },
    ],
    custom: {
      enabled: false,
    },
  },

  seatOuter: {
    label: "Seat Outer",
    defaultValue: "Black Merino",
    meshNames: ["Seat_Outer", "Seat_Outer.001"],
    materialNames: [],
    keywords: [],
    material: {
      metalness: 0.02,
      roughness: 0.84,
      clearcoat: 0.02,
      clearcoatRoughness: 0.48,
      envMapIntensity: 0.28,
    },
    colors: [
      { name: "Black Merino", value: "#1b1817", price: 0 },
      { name: "Anthracite", value: "#3a322d", price: 5900 },
      { name: "Tartufo", value: "#604131", price: 5900 },
    ],
    custom: {
      enabled: false,
    },
  },
};

export default BMW_M4_Coupe_Competition;
