const bmwX7M60iConfig = {
  id: "BMW X7 M60i",
  name: "BMW X7 M60i",
  basePrice: 970000,

  scene: {
    cameraAngle: 12,
    cameraHeight: 1.2,
    zoom: 5.5,
    fov: 50,
    carAngle: -36,
    maxRotationX: 90,
    maxRotationY: 180,
    light: 0.45,
    shadow: 0.75,
    background: "#ffffff",
    target: [0, 0.15, 0],
    minDistance: 0,
    maxDistance: 7,
    intro: {
      enabled: true,
      startHeight: 8,
      duration: 1200,
      animateBetweenPositions: true,
    },
  },

  orderScene: {
    cameraAngle: 12,
    cameraHeight: 1.2,
    zoom: 5.5,
    fov: 50,
    carAngle: -36,
    maxRotationX: 90,
    maxRotationY: 180,
    light: 0.45,
    shadow: 0.75,
    background: "#ffffff",
    target: [0, 0.15, 0],
    minDistance: 0,
    maxDistance: 7,
    positions: [
      {
        id: "body",
        label: "Body",
        scene: {
          cameraAngle: 12,
          cameraHeight: 1.2,
          zoom: 5.5,
          fov: 50,
          carAngle: -36,
          maxRotationX: 90,
          maxRotationY: 180,
          light: 0.45,
          shadow: 0.75,
          background: "#ffffff",
          target: [0, 0.15, 0],
          minDistance: 3.4,
          maxDistance: 7,
        },
      },
      {
        id: "inside",
        label: "Inside",
        scene: {
          cameraAngle: 0,
          cameraHeight: 0.7,
          zoom: 0.16,
          fov: 90,
          carAngle: 0,
          maxRotationX: 0,
          maxRotationY: 360,
          background: "#ffffff",
          target: [0, 0.6, 0.3],
          minDistance: 0.18,
          maxDistance: 7,
        },
      },
    ],
    intro: {
      enabled: false,
    },
  },

  customizable: {
    steps: [
      {
        id: "paint",
        type: "paint",
        label: "Body Color",
        scene: {
          cameraAngle: 12,
          cameraHeight: 1.2,
          zoom: 5.5,
          fov: 50,
          carAngle: -36,
          maxRotationX: 90,
          maxRotationY: 180,
          light: 0.45,
          shadow: 0.75,
          background: "#ffffff",
          target: [0, 0.15, 0],
          minDistance: 3.4,
          maxDistance: 7,
          intro: {
            enabled: true,
            startHeight: 8,
            useLast: true,
            duration: 1200,
          },
        },
      },
      {
        id: "rims",
        type: "rims",
        label: "Rim Color",
        scene: {
          cameraAngle: 90,
          cameraHeight: 0.22,
          zoom: 5.34,
          fov: 50,
          carAngle: 0,
          maxRotationX: 90,
          maxRotationY: 180,
          light: 0.6,
          shadow: 0.8,
          background: "#ffffff",
          target: [0, 0, 0],
          minDistance: 3.2,
          maxDistance: 7,
          intro: {
            enabled: true,
            startHeight: 8,
            duration: 850,
            useLast: true,
          },
        },
      },
      {
        id: "seats",
        type: "seats",
        label: "Seat Colors",
        scene: {
          light: 0.5,
          shadow: 0.35,
          positions: [
            {
              id: "inside",
              label: "Inside",
              scene: {
                cameraAngle: 0,
                cameraHeight: 0.73,
                zoom: 0.23,
                fov: 85,
                carAngle: 0,
                maxRotationX: 0,
                maxRotationY: 360,
                light: 0.5,
                shadow: 0.35,
                background: "#ffffff",
                target: [0, 0.6, 0.3],
                minDistance: 0.18,
                maxDistance: 7,
                intro: {
                  enabled: true,
                  startHeight: 100,
                  duration: 900,
                  transition: "orbit",
                  useLast: true,
                  animateBetweenPositions: true,
                },
              },
            },
            {
              id: "outside",
              label: "Outside",
              scene: {
                cameraAngle: 24,
                cameraHeight: 1.45,
                zoom: 4.1,
                fov: 48,
                carAngle: -18,
                maxRotationX: 90,
                maxRotationY: 180,
                light: 0.5,
                shadow: 0.35,
                background: "#ffffff",
                target: [0, 0.55, 0],
                minDistance: 3.8,
                maxDistance: 7,
                intro: {
                  enabled: false,
                  startHeight: 1.9,
                  duration: 700,
                  transition: "orbit",
                  useLast: false,
                },
              },
            },
          ],
          intro: {
            enabled: false,
            startHeight: 1.9,
            duration: 700,
            transition: "orbit",
            useLast: false,
          },
        },
      },
      {
        id: "glassTint",
        type: "glassTint",
        label: "Window Tint",
        scene: {
          cameraAngle: 12,
          cameraHeight: 1.2,
          zoom: 5.5,
          fov: 50,
          carAngle: -36,
          maxRotationX: 90,
          maxRotationY: 180,
          light: 0.45,
          shadow: 0.75,
          background: "#ffffff",
          target: [0, 0.15, 0],
          minDistance: 3.4,
          maxDistance: 7,
          intro: {
            enabled: true,
            startHeight: 8,
            useLast: true,
            duration: 1200,
          },
        },
      },
    ],
  },

  paint: {
    label: "Body Color",
    defaultValue: "Dravit Grey",

    meshNames: [],
    materialNames: ["inmx7m60i_body", "bodyshell.6", "f_bump1.5"],
    keywords: [],

    material: {
      metalness: 0.8,
      roughness: 0.2,
      clearcoat: 0.2,
      clearcoatRoughness: 0.08,
      envMapIntensity: 1.25,
    },

    colors: [
      { name: "Dravit Grey", price: 0 },
      { name: "Alpine White", price: 7900 },
      { name: "Black Sapphire", price: 12900 },
      { name: "Portimao Blue", price: 18900 },
      { name: "Tanzanite Blue", price: 18900 },
      { name: "Brooklyn Grey", price: 14900 },
      { name: "San Remo Green", price: 14900 },
    ],

    custom: {
      enabled: false,
    },
  },

  rims: {
    label: "Rim Color",
    defaultValue: "Black",

    meshNames: [
      "inmx7m60i_wheel_inmx7m60i_black_0",
      "inmx7m60i_wheel.001_inmx7m60i_black_0",
      "inmx7m60i_wheel.002_inmx7m60i_black_0",
      "inmx7m60i_wheel.003_inmx7m60i_black_0",
    ],

    materialNames: [],

    keywords: [
      "inmx7m60i_wheel_inmx7m60i_black_0",
      "inmx7m60i_wheel.001_inmx7m60i_black_0",
      "inmx7m60i_wheel.002_inmx7m60i_black_0",
      "inmx7m60i_wheel.003_inmx7m60i_black_0",
    ],

    material: {
      metalness: 0.75,
      roughness: 0.18,
      clearcoat: 0.4,
      clearcoatRoughness: 0.12,
      envMapIntensity: 1.1,
    },

    colors: [
      { name: "Black", price: 0 },
      { name: "Silver", price: 5900 },
      { name: "Gunmetal", price: 5900 },
      { name: "Bronze", price: 9900 },
      { name: "White", price: 3900 },
    ],

    custom: {
      enabled: false,
    },
  },

  seatOuter: {
    label: "Seat Color",
    defaultValue: "Black Merino",
    meshNames: [],
    materialNames: [],
    keywords: ["seat_FR", "seat_FL", "seat_back"],
    material: {
      metalness: 0.02,
      roughness: 0.84,
      clearcoat: 0.02,
      clearcoatRoughness: 0.48,
      envMapIntensity: 0.28,
    },
    colors: [
      { name: "Black Merino", value: "#1b1817", price: 0 },
      { name: "Anthracite", value: "#3a322d", price: 5900 },
      { name: "Tartufo", value: "#604131", price: 5900 },
      { name: "Gray", value: "#706e6e", price: 7900 },
    ],
    custom: {
      enabled: false,
    },
  },

  glassTint: {
    label: "Window Tint",
    defaultValue: "Factory",
    meshNames: [],
    materialNames: ["inmx7m60i_glass"],
    keywords: [],
    excludeKeywords: ["headlight", "taillight", "tailglass", "mirror", "misc"],
    material: {
      metalness: 0,
      roughness: 0.08,
      clearcoat: 0.05,
      clearcoatRoughness: 0.02,
      envMapIntensity: 1.1,
      transparent: true,
      opacity: 0.72,
    },
    colors: [
      {
        name: "Factory",
        value: "#000001",
        price: 0,
        material: {
          opacity: 0.2,
        },
      },
      {
        name: "Privacy",
        value: "#000002",
        price: 11000,
        material: {
          opacity: 0.5,
        },
      },
      {
        name: "Executive",
        value: "#000000",
        price: 14000,
        material: {
          opacity: 0.7,
        },
      },
    ],
    custom: {
      enabled: false,
    },
  },
};

export default bmwX7M60iConfig;